### ISSUE TITLE
load maplace asynchronously

### ISSUE THREAD

**Issue by Marc-pi** [danielemoraschi/maplace.js#100]
@danielemoraschi,
is there a way to load your lib asynchronously, to speed up pages load time and not block rendering
- for google maps API V3, google advises this https://developers.google.com/maps/documentation/javascript/examples/map-simple-async with with window.onload
- but with your call, how to do that ?

thanks for your help

**Comment by Marc-pi** [comment]
@danielemoraschi any help on this?

**Comment by Marc-pi** [comment]
@danielemoraschi , we were able to add async for a simple marker, but not for a more complex usage of maplace
can you have a look and help us to implement this https://developers.google.com/maps/documentation/javascript/tutorial#asynch , so it is by default set for the whole maplace lib as default behavior?

**Comment by Marc-pi** [comment]
if you can have a look on this, would be appreciated !

**Comment by danielemoraschi** [comment]
Hi,

you can try something like that:
```javascript
<script>
    function initMaplace () {
        new Maplace({...}).Load()
    }
    
    function maplace() {
        var d = document, 
            t = 'script',
            o = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        o.src = 'dist/maplace.min.js';
        o.addEventListener('load', function (e) { 
            initMaplace(); 
        });
        s.parentNode.insertBefore(o, s);
    }
</script>

<script src="https://maps.google.com/maps/api/js?sensor=false&amp;libraries=geometry&amp;v=3.22&callback=maplace"></script>
```

**Comment by Marc-pi** [comment]
thx, we'll test, 
but you could add this **by default** in the doc/distro. 
Async is important for page loading times, especially on mobile.

**Comment by danielemoraschi** [comment]
Async is more useful when you don't care when the script loads and nothing else depends upon that script loading. Maplace is not really a good candidate, to achieve the same result it's enough for you to keep the scripts right before the closing </body> and after all the other scripts in your page, so the page will be parsed and rendered completely before reaching that point.
If a second script depends upon the first script (e.g. Maplace which uses both jQuery and GoogleMap), then you can't make it async without additional code to control the execution order, but you are not really gaining any real speed improvements from a user point of view.

**Comment by Marc-pi** [comment]
yes, that's what i tested few months ago. The script dependency toward JQuery and GoogleMap make things difficult.  => Who is firing who is the question !! 
maybe we need a RequireJS lib (or similar) for instance, but we never ding into this
