### ISSUE TITLE
Google Map usage quota query

### ISSUE THREAD

**Issue by lajpatshah** [danielemoraschi/maplace.js#102]
Hi
Can you plz inform whether there is any usgae quota for using the reference google map js?
On google map api the reference js is different from what you are using. Hence I am not sure if the limit applies to your reference js as well?
There is no mention of api key in the reference js used by you. 
Kindly plz revert
Sincere thanks
Lajpat

**Comment by Marc-pi** [comment]
just add the extram param and you are done
it is advised by Google itself to add this param, even if you do not reach the quota
@danielemoraschi would be nice to set this as default in the distro

**Comment by danielemoraschi** [comment]
what's the parameter are you referring to?

**Comment by Marc-pi** [comment]
hello, 
see https://developers.google.com/maps/documentation/javascript/get-api-key
this is the API Key, that is recommended, even if you do not reach the quota.
i guess it's quicker with the key than without...

**Comment by danielemoraschi** [comment]
I know about the API key but it has nothing to do with plugin. The Google Map script doesn't come with Maplace, has to be included manually

**Comment by Marc-pi** [comment]
yes, that's what's  was told there https://github.com/danielemoraschi/maplace.js/issues/102#issuecomment-101704504, but the doc can be tweeked for that http://maplacejs.com/#Setup
