### ISSUE TITLE
remove markers

### ISSUE THREAD

**Issue by abhishekscript** [danielemoraschi/maplace.js#114]
Ho do I remove Marker that are showing on this map. I tried calling setMap(null) but the marker stays on.

    var Circles = [
    {
        lat: 18.9750,
        lon: 72.8258,
        circle_options: {
            radius: 1000
        }
    },
	    {
        lat: 28.6139,
        lon:77.2090,
        circle_options: {
            radius: 1000
        }
    }
];
function showdemography() {
new Maplace({
    locations: Circles,
    map_div: '#gmap-circles',
    start: 4,
    view_all_text: 'Points of interest',
    type: 'circle',
    shared: {
        zoom: 16,
        html: '%index'
    },
    circleRadiusChanged: function(index, point, marker) {
      $('#radiusInfo').text(
        ' - point #' + (index+1) + ' size: ' + parseInt(marker.getRadius()) + 'mt.'
      );
    }
}).Load();
}

**Comment by danielemoraschi** [comment]
Hi,
you can use SetLocations or RemoveLocations methods as per documentation.
http://jsfiddle.net/_tomorro/cmL2z06a/1/
