### ISSUE TITLE
adding vars to menu listing

### ISSUE THREAD

**Issue by designdennings** [danielemoraschi/maplace.js#115]
im using a seperate menu somewhat like the demo, i want to add information below the title (like date and location) and be able to style these with css. i don't know where to add these.can someone help me along?

**Comment by danielemoraschi** [comment]
I think you can simply try something like:
```
var locations = [
    {
        lat: 45.9,
        lon: 10.9,
        title: 'Title<br/><small>small text</small>',
        html: 'Content'
    },
    ...
];
```
