### ISSUE TITLE
stroke_options not working

### ISSUE THREAD

**Issue by jeffceriello** [danielemoraschi/maplace.js#120]
Ciao Daniele, ti scrivo in inglese cosi magari puo' essere utile anche ad altri.

I have a new Maplace with these settings

new Maplace({
          locations: locations,
          map_div: '#gmap-route',
          generate_controls: false,
          //controls_type: 'list',
          show_markers: true,
          type: 'directions',
          draggable: true,
          directions_panel: '#route',
          styles: styles,
          stroke_options: {
              strokeColor: '#161616',
              strokeOpacity: 0.8,
              strokeWeight: 20,
              fillColor: '#161616',
              fillOpacity: 0.4
          },
          map_options: {
            scrollwheel: false,
            zoom: 8
          },
          afterRoute: function(distance) {
              jQuery('#km').text(': '+(distance/1000)+'km');
          }
      }).Load();

But stroke options doesn't work at all. I have looked everywhere but I can't find a solution to this. The documentation says it should work with type: directions. Can you spot if I'm doing anything wrong?

Grazie
Jeff

**Comment by danielemoraschi** [comment]
If you try this it will work.
I've commented out the variable styles as is not part of your example.
```
new Maplace({
  locations: LocsB,
  map_div: '#gmap-route',
  generate_controls: false,
  //controls_type: 'list',
  show_markers: true,
  type: 'directions',
  draggable: true,
  directions_panel: '#route',
  //styles: styles,
  stroke_options: {
    strokeColor: '#161616',
    strokeOpacity: 08,
    strokeWeight: 20,
    fillColor: '#161616',
    fillOpacity: 04
  },
  map_options: {
    scrollwheel: false,
    zoom: 8
  },
  afterRoute: function(distance) {
    //$('#km').text(': '+(distance/1000)+'km');
  }
}).Load();
```

**Comment by danielemoraschi** [comment]
I've just realised that there's no support for stroke options by Google using directions.
FYI https://groups.google.com/forum/#!topic/google-maps-js-api-v3/I9J1McAcEIY

**Comment by jeffceriello** [comment]
Oh I see, that's why. Thank you for looking into it anyway.
