### ISSUE TITLE
Waypoints limit with type directions

### ISSUE THREAD

**Issue by jeffceriello** [danielemoraschi/maplace.js#121]
After digging into google's documentation I learned that there is a limit of 8 waypoints in total without the Google Maps Directions API Key, but I need more than 8.

The directions request should look like this
http://maps.googleapis.com/maps/api/directions/output?parameters

https://maps.googleapis.com/maps/api/directions/json?origin=Toronto&destination=Montreal&key=YOUR_API_KEY

How can I enter my Directions API Key?

Thank you

**Comment by danielemoraschi** [comment]
Please refer to the documentation provided by Google:
https://developers.google.com/maps/documentation/javascript/tutorial#api_key
