### ISSUE TITLE
Function Load

### ISSUE THREAD

**Issue by Salvagm** [danielemoraschi/maplace.js#122]
Hi! I'm working in a proyect and I'm using your library. I've made a menu custom for show an information table, but when this table have got one element doesn't show anything.

I found in the source code that in function Load (line 1070) in generate controls checks if this.ln > 1. I've changed this condition to this.ln > 0 and it works fine for me.
I don't know if this is a bug or it's should be there

Thank you very much for the library, it's very helpful in my proyect =)!
Thanks, Salva.
PD: Sorry my broken english.

**Comment by danielemoraschi** [comment]
Hi,

there is a setting to force generate the menu item also with one single location (set to false by default):
<code>force_generate_controls: true|false</code>

I hope it helps.
Thanks

**Comment by Salvagm** [comment]
Hi,

Thank you for the answere, I must read the documentation carefully. I've changed my code and it works =D!

Thanks, 
Salva
