### ISSUE TITLE
how to render multiple maps on single page?

### ISSUE THREAD

**Issue by ashish-joshi-nct** [danielemoraschi/maplace.js#124]
i used below code to initialize multiple maps on a page.. but i am getting only one map instead..
`//dropdown example
new Maplace({
    locations: LocsA,
    map_div: '.gmap-dropdown',
    controls_title: 'Choose a location:'
}).Load();

//ul list example
new Maplace({
    locations: LocsB,
    map_div: '.gmap-list',
    controls_type: 'list',
    controls_title: 'Choose a location:'
}).Load(); `

**Comment by danielemoraschi** [comment]
Could you please paste your html as well?

**Comment by ashish-joshi-nct** [comment]
It was a little bit tricky but i solved it... here is the way i did that...

HTML:

<li class="map_view">
	<div class="white_back">
		<ul class="gen_list">
			<div class="gmap-dropdown"></div>
			<div class="gmap-list" style="height:300px; width:800px;"></div>
		</ul>
	</div>
</li>

<li class="map_view">
	<div class="white_back">
		<ul class="gen_list">
			<div class="gmap-dropdown"></div>
			<div class="gmap-list" style="height:300px; width:800px;"></div>
		</ul>
	</div>
</li>


jQuery:

        var vars = {};
        var i = 0;
        $(".gmap-list").each(function() {
            i++;                        
            var LocsA = [{
                lat: 55.6,
                lon: 36,
                title: 'Title A1',
                html: '&lt;h3&gt;Content A1&lt;/h3&gt;',
                icon: 'http://maps.google.com/mapfiles/markerA.png',
                animation: google.maps.Animation.DROP
            }];
            
            vars['map' + i] = new Maplace({
                locations: LocsA,
                map_div: '.gmap-dropdown',
                controls_title: 'Choose a location:'
            })
            vars['map' + i].Load();

            //ul list example
            vars['list' + i] = new Maplace({
                locations: LocsA,
                map_div: $(this),
                controls_type: 'list',
                controls_title: 'Choose a location:'
            });
            vars['list' + i].Load();
        });
