### ISSUE TITLE
Actuall example of listener in use.

### ISSUE THREAD

**Issue by sagive** [danielemoraschi/maplace.js#127]
#i can't seem to find an actual example of listener in use

i tried doing this:

```
mainmap = new Maplace({  
	locations: newLoc,  
	map_div: '#gmap',
	generate_controls: true,
	controls_on_map: false,
	controls_title: '',
	listeners: {
		click: function(map, event) {
			console.log('TEST');
		}
	}
}).Load();
```

But that "test" string seems to appear only on load (once) and than i get no reaction to the click.
Am i way off? can you share a complete example or point me in the right direction?

**Comment by stephandesouza** [comment]
Hey @sagive, i stopped in the same problem. The listener options is working well using the devel branch.

ping @danielemoraschi
