### ISSUE TITLE
Help with routes, please! (Number of locations)

### ISSUE THREAD

**Issue by Niko-EstudioBL** [danielemoraschi/maplace.js#129]
Hi Daniel! How are you?
First, sorry for my english haha I'm from Argentina, and my english is not very well.

I use your JS for some time, and I find it amazing. But I'm with a new job, and I'm having difficulties following a route. I may not mark more than 10 locations, from 11 onwards, the route disappears. 
Is there a way to fix it?

And is there a way to hide the markers that appear at the beginning and end of the route? I would like to stay only led the way.

Please, help me. 
Thank you very much in advance!

:)

**Comment by danielemoraschi** [comment]
Hi Niko,

if you can please build up an example of what you are trying to do in
JsFiddle.
I can help you from there.

You can fork mine if you want:
https://jsfiddle.net/_tomorro/yhrmL5zz/

Thanks

On Wed, Feb 24, 2016 at 3:52 PM, Niko-EstudioBL <notifications@github.com>
wrote:

> Hi Daniel! How are you?
> First, sorry for my english haha I'm from Argentina, and my english is not
> very well.
>
> I use your JS for some time, and I find it amazing. But I'm with a new
> job, and I'm having difficulties following a route. I may not mark more
> than 10 locations, from 11 onwards, the route disappears.
> Is there a way to fix it?
>
> And is there a way to hide the markers that appear at the beginning and
> end of the route? I would like to stay only led the way.
>
> Please, help me.
> Thank you very much in advance!
>
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielemoraschi/maplace.js/issues/129>.
>



-- 
Daniele Moraschi

12 Chaplin Apartments, 5 Sylvester Path
E8 1EN, London - UK

m. +44 770 803 2519

**Comment by tenKinetic** [comment]
Not sure about the issue of > 10 locations not displaying, but your other question about hiding markers may be the same as [issue 31](https://github.com/danielemoraschi/maplace.js/issues/31)?
