### ISSUE TITLE
Maplace with JQuery Geocomplete

### ISSUE THREAD

**Issue by themanish** [danielemoraschi/maplace.js#131]
I'm trying to integrate jquery geocomplete with maplace. So that location suggestion from geocomplete & route display from maplace can be achieved. But something is not going good. Help please.
Below is my jsFiddle Link:
https://jsfiddle.net/manishrestha529/bruf4ndo/6/

**Comment by tenKinetic** [comment]
I updated the fiddle: https://jsfiddle.net/bruf4ndo/8/
I have had issues with an update to an existing map before and had solved it by clearing the target container before loading again. You'll see I've simply done this on the line after your alert('both'). It would be good to have the map extended without a full reload, but this method has worked fine for me in all cases so far.
