### ISSUE TITLE
Hide/Show show_infowindow on page load

### ISSUE THREAD

**Issue by richardmint** [danielemoraschi/maplace.js#133]
Is it possible to have the Info Window be hidden when the page loads, but when clicking on a marker, the corresponding Info Window will open? Thanks

**Comment by tenKinetic** [comment]
This can be done by overriding the very first time beforeShow is triggered. This first trigger is the automatic one.
When creating your map define beforeShow something like:
```
beforeShow: function(index, location, marker) {
  if (!location.closedOnInit)
  {
    location.closedOnInit = true;
    marker.info.close();
  }
}
```
There may be different behaviour for 1 location vs many locations. In my implementation the InfoWindow does not automatically show when there are > 1 locations. The code above does not cause any problem when this is the case though. If necessary you can add a check of marker count and exit the function if that count is > 1.

**Comment by VeeK727** [comment]
For some reason, it messes with my zoom settings. When the page loads, the map get's zoomed in all the way (but the info_window was closed) and when you click on it, the window opens and zoom is set to the correct setting of 15. Any idea why?

```
   var LocsD = [
    {
      lat: 26.688348,
      lon: 87.133615,
      title: 'Some Title',
      html: [
      	'<h4>Heading</h4>',
      	'<p>1234, Somewhere in, the Vicinity of, India</p>'
      ].join(''),
      zoom: 15
    }
	];
	var maplace = new Maplace({
    locations: LocsD,
    map_div: '#gmap',
    generate_controls: true,
    show_markers: true,
    type: 'marker',
    draggable: true,
    beforeShow: function(index, location, marker) {
		  if (!location.closedOnInit)
		  {
		    location.closedOnInit = true;
		    marker.info.close();
		  }
		},
    afterRoute: function(distance) {
        $('#route').text(': '+(distance/1000)+'km');
    }
  }).Load();
```

**Comment by tenKinetic** [comment]
It looks like it's because you have associated the zoom level of 15 only with your location and not the map itself. When you click your location it uses the zoom of 15 associated with the location. To get the map to zoom to 15 when it loads I think you need to add the map_options parameter which is an object that contains zoom (amongst other things): `{zoom:15}`.

```
    var LocsD = [
    {
      lat: 26.688348,
      lon: 87.133615,
      title: 'Some Title',
      html: [
        '<h4>Heading</h4>',
        '<p>1234, Somewhere in, the Vicinity of, India</p>'
      ].join(''),
      zoom: 15
    }
    ];
    var maplace = new Maplace({
    locations: LocsD,
    map_div: '#gmap',
    generate_controls: true,
    show_markers: true,
    type: 'marker',
    draggable: true,
    map_options:{zoom:15},
    beforeShow: function(index, location, marker) {
          if (!location.closedOnInit)
          {
            location.closedOnInit = true;
            marker.info.close();
          }
        },
    afterRoute: function(distance) {
        $('#route').text(': '+(distance/1000)+'km');
    }
  }).Load();
```

**Comment by VeeK727** [comment]
Excellent. It worked. Thanks. I think Daniel needs a more detailed documentation since this is such a complicated topic. Some examples would really go a long away.
