### ISSUE TITLE
1 menu item triggers 2 locations possible?

### ISSUE THREAD

**Issue by jakubzwierzynski** [danielemoraschi/maplace.js#143]
Just a quick question, is it possible to add 2 markers (with info windows) to one location?

What i need is to setup 1 menu/controll item, when clicked, 2 markers show their info window.

Any help would be appreciated.

**Comment by danielemoraschi** [comment]
Will the markers be on different locations on the map?

**Comment by jakubzwierzynski** [comment]
Yes, its basically for 2-3 buildings close to each other (developer with couple of flats to sell in each building)

**Comment by danielemoraschi** [comment]
could you provide a live demo? like in jsFiddle?
