### ISSUE TITLE
InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama

### ISSUE THREAD

**Issue by mahendhar9** [danielemoraschi/maplace.js#145]
The following error appears in the console.
The error shows up on all the other pages except in the page of the map.

InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama 
InvalidValueError: setMap: not an instance of Map
Uncaught TypeError: Cannot assign to read only property

Following is the code
`var data = [{
  lat: gon.start_lat,
  lon: gon.start_long,
    zoom: 8,
    icon: 'http://www.google.com/mapfiles/markerA.png'
  },{
    lat: gon.end_lat,
    lon: gon.end_long,
    icon: 'http://www.google.com/mapfiles/markerB.png'
  }
  ];`

`new Maplace({
    locations: data,
    map_div: '#gmap-route',
    generate_controls: false,
    type: 'directions',
    draggable: false,
  }).Load();`

**Comment by danielemoraschi** [comment]
Hi,

you must have some invalid value for gon.start_lat or gon.start_long. If you try to hardcode numeric parameters in you data object your code works just fine.

**Comment by mahendhar9** [comment]
Thank you @danielemoraschi. The gon variables were undefined.
