### ISSUE TITLE
Could not add locations to map using Ajax

### ISSUE THREAD

**Issue by pressaholic** [danielemoraschi/maplace.js#149]
Hi there,

First of all, thanks for this marvelous tool.

I am loading a map using a locations array as defined on your doc, and that works.
Then i use ajax to get more locations, and on the callback i tried map_object.AddLocations($new_locations, true); but it doesnt work.

Any help ?

**Comment by danielemoraschi** [comment]
Are you calling "map_object.Load()" to update the view after having added new locations?

**Comment by pressaholic** [comment]
I am using the second parameter of AddLocations set to true to reload the map.
Actually, the map reloads with the initial locations loaded at map declaration, without the new ones.

**Comment by danielemoraschi** [comment]
can you share a jsfiddle so I can check? you can fork from this one: https://jsfiddle.net/_tomorro/yhrmL5zz/

**Comment by pressaholic** [comment]
Hi again,

I have created a jsfiddle here : https://jsfiddle.net/r85tfm83/2/.
It is working pretty smoothly, since i am declaring the new items variable
manually.

In my real code, i have json encoded a PHP array that is received through
an AJAX call.
Maybe that's what is breaking my code.

Any thoughts ?



-----------------------------------------------------------------------
*pressaholic*
Wordpress and PHP Web Development
http://pressaholic.com

2016-08-23 21:39 GMT+00:00 D. Moraschi <notifications@github.com>:

**Comment by danielemoraschi** [comment]
I think you probably have some invalid data in your json. Could you please double check on that? I'll see if I can add more logging to the library.

**Comment by pressaholic** [comment]
Hi again,

Thanks a lot for your help.
I had the icon property of the location object, that was invalid.
Problem solved :)

Two more questions :
1/ Can you recommend an alternative for the Gmaps default info window?
2/ How can i set the map to match the full height of the viewport ?

Thanks again.



-----------------------------------------------------------------------
*pressaholic*
Wordpress and PHP Web Development
http://pressaholic.com

2016-08-24 11:04 GMT+00:00 D. Moraschi <notifications@github.com>:

**Comment by danielemoraschi** [comment]
1) Maplace support only the standard `google.maps.InfoWindow`. If you wish you can extend Maplace to include your own infowindow type in this way:
```
Maplace.prototype.type_to_open.mytype = function(location) {
    this.infowindow = {
        open: function() {
            alert(location.html);
        },
        close: function() {}
    }
}
    
new Maplace({
    type:'marker',
    infowindow_type: 'mytype',
    locations:[{
        lat:0,
        lon:0,
        html:'Hello'
    }]
}).Load();   
```

2) Just size properly via CSS the div containing the map.
