### ISSUE TITLE
Alter Content HTML dynamically

### ISSUE THREAD

**Issue by jccalbuquerque** [danielemoraschi/maplace.js#153]
You can change the HTML content of Locations?
For example: I have a marker on the map with html  `'<h3> test </ h3>'` dynamically want to change that content to `'<h3> Pass </ h3>'`.
I am using a setPosition function to change the position of the marker, so I need to update the contents of location.html
Is this possible?

**Comment by parubabr** [comment]
Hi, use the event beforeOpenInfowindow:

beforeOpenInfowindow: function(index, location, marker) {
    location.html = '<h3> Pass </ h3>';
}
