### ISSUE TITLE
Specify center of the map for multiple pins

### ISSUE THREAD

**Issue by VeeK727** [danielemoraschi/maplace.js#156]
I have two locations on the map and two markers are appearing in the desired location, however the automatic center point calculated to fit the two markers is not correct. Here's how it looks like
![73](https://cloud.githubusercontent.com/assets/11595460/20858027/d9b73136-b960-11e6-8cdb-2eabe2e46526.jpg)

Here's how it should look like
![74](https://cloud.githubusercontent.com/assets/11595460/20858032/e33a9edc-b960-11e6-8228-55b90d1837a9.jpg)

So the center of markers are coming in the pacific ocean, but I want it to be in the atlantic ocean. I've tried the center options of google api but it had no effect.

```
new Maplace({
        map_div: '#map',
	locations: markersData,
	generate_controls: false,
	map_options: {
		center: new google.maps.LatLng(34.679859, -13.858490),
		zoom: 3
	}
}).Load();
```

**Comment by danielemoraschi** [comment]
As per documentation, the setting is: `set_center: [<lat>, <lon>],`
