### ISSUE TITLE
What goes in the AJAX.php file?

### ISSUE THREAD

**Issue by ryanderson** [danielemoraschi/maplace.js#157]
I'm try to follow the Mixed/Ajax example...but what goes in the ajax.php file that is referenced in the js code snippet?

**Comment by ryanderson** [comment]
Ok, found your reference file. In the code example it reads:

`$.getJSON('data/ajax.php', { type: index }, function(data) {`

but your referemce file is actually located @:

`$.getJSON('website/data/ajax.php', { type: index }, function(data) {`

So https://maplacejs.com/website/data/ajax.php, which has this in it (Group A tab information):

`{"title":"Group A","type":"marker","locations":[{"lat":45.9,"lon":10.9,"title":"Title A1","html":"<h3>Content A1</h3>","icon":"http://maps.google.com/mapfiles/markerA.png"},{"lat":44.8,"lon":1.7,"title":"Title B1","html":"<h3>Content B1</h3>","icon":"http://maps.google.com/mapfiles/markerB.png","show_infowindow":false},{"lat":51.5,"lon":-1.1,"title":"Title C1","html":"<h3>Content C1</h3><p>Lorem Ipsum..</p>","zoom":8,"icon":"http://maps.google.com/mapfiles/markerC.png"}]}`

But where is Group B, Group C and Group D and Group E from the example? And how are they loaded?

**Comment by danielemoraschi** [comment]
Here's the file:
https://github.com/danielemoraschi/maplace.js/blob/master/website/data/ajax.php

I'm just using a GET variable "type" to switch between the groups.

**Comment by ryanderson** [comment]
Doh! I didn't think to look at the GitHub files. My bad. Thank you for the quick reply. This is exactly what I need. Any chance you have an example of how to get the default tab to show ALL the markers from all tabs?

**Comment by danielemoraschi** [comment]
That's something you'll have to implement on your side, since a tab is a pure UI component. You can for example crete a logical first tab as an array merge of all the locations.
