### ISSUE TITLE
Location Search?

### ISSUE THREAD

**Issue by alexmkubik** [danielemoraschi/maplace.js#165]
Kind of a Noob here, but am I missing something... Is there any simple or recommended way for a form field where users can enter their location and find all markers within a radius?

**Comment by danielemoraschi** [comment]
Given that you know how to create a form field to reverse geocode an address and having a list of initial locations; once found the address coordinates you can iterate through the array of locations and filter out the ones outside the radius then instantiate Maplace with the ones remaining.

Some useful links: 
- https://developers.google.com/maps/documentation/javascript/examples/geocoding-simple
- http://stackoverflow.com/questions/23115375/determine-if-a-longitude-latitude-co-ordinate-is-inside-a-radius-in-miles-and

**Comment by alexmkubik** [comment]
Wow! Thank you for the links, that response was very fast!!!
