### ISSUE TITLE
How to add new marker?

### ISSUE THREAD

**Issue by malinga91** [danielemoraschi/maplace.js#168]
Using my application, users should be able to select a New location then enter details about the location. How can I do this?

**Comment by danielemoraschi** [comment]
Please refer to the documentation on the website, as you can use the methods `SetLocations `, `AddLocation`, or `AddLocations` to achieve that.
Something like:
```
var myMap = new Maplace({
    type:'marker',
    locations:[{
        lat: 0, 
        lon: 0,
        html:'Hello 1'
    }]
});

myMap.Load();
        
setTimeout(function() {
    mm.AddLocations({
        lat: 1, 
        lon: 1,
        html: 'Hello 2'
    }, true);
}, 3000);
```

**Comment by malinga91** [comment]
@danielemoraschi  I got it. I need something like this. User login to the application. Then click on a button call +Add new place. Then user should see a draggable marker. user can drag and place the marker. After placing marker lng, lat can be get. Otherwise how users can get lng, lat?

**Comment by danielemoraschi** [comment]
For this kind of implementations I suggest you to study GoogleMaps Javascript API starting from here: https://developers.google.com/maps/documentation/javascript/tutorial

Also, Google is your best friend: https://www.google.com/search?q=google+maps+click+place+marker&oq=google+maps+click+place&aqs=chrome.1.69i57j0l3j69i64l2.15367j0j4&sourceid=chrome&ie=UTF-8

**Comment by danielemoraschi** [comment]
Hope this will help: http://jsfiddle.net/_tomorro/jm48rx8y/
