### ISSUE TITLE
If map is loaded via ajax in bootstrap dialog, browser window must be resized to display map

### ISSUE THREAD

**Issue by Nicero** [danielemoraschi/maplace.js#173]
I noticed that when I load a second time the same map inside a boostrap dialog, I need to resize the browser's window to force map reload.
1. I click a link in `index.php`
2. `map.php` is loaded via ajax. The map is correctly diplayed inside a dialog
3. I click the Cancel button of the dialog. The dialog closes.
4. I click a second time the same link in `index.php`
5. The `#gmap` div appears grey (Only the links "Google" and "Terms & condition" are shown at the bottom) of the div.

`console.log` shows only one line `http://localhost/myapp/map.php` while normally a lot of data is loaded. It seems that loading gets stuck.

At this point, if I resize just a little the browser's window, loading resumes and the map is displayed correctly. This happens both in Firefox 54 and Chrome 58.

When I resize the window `console.log` reports the following line as the first line before all the other data is loaded:

`https://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo`

Before adopting `maplace.js` I did used in the same web site google maps API in the "traditional" way as explained by Google and I did not have this issue:

    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 17,
            center: myLatLng,
            mapTypeControl: false,
            streetViewControl: false
        })
    }

May I force reload/refresh of the map/div?

Enrico

**Comment by Nicero** [comment]
**SOLVED** by adding `setTimeout()`

    function showMap(){	
        maplace.Load({
            controls_on_map: false,
            locations: [{
                 lat: 45.64953, 
                 lon: 13.77682,
                 zoom: 17
            }]
       });
    }
				
    setTimeout(showMap, 500);

**Comment by danielemoraschi** [comment]
Could you try forcing the resize event on the map?
```
google.maps.event.trigger(maplaceObj.oMap, 'resize');
```

**Comment by Nicero** [comment]
This issue - the browser window must be resized to display map - is a known issue. The best explanation may be that we are trying to render the area before the element is shown in the DOM. For this reason some suggest to set a `TimeOut` others suggest to force a resize. 
I noticed this issue in maplacejs.com web site too when I switch multiple times between `code` and `example`.
Both the solution worked for me.
Thank you
