### ISSUE TITLE
Using sample code, browser can not show Google map at all.

### ISSUE THREAD

**Issue by stonez56** [danielemoraschi/maplace.js#175]
Hi! This is supposed to be a quick test of Mplace.js, but it didn't work.
Please help!

**ERROR**: Uncaught TypeError: Cannot read property js?key=MyGoogleAPIKEY&libraries=geometry 
             'idle' of undefined
              at Dc (js?key=MyGoogleAPIKEY&libraries=geometry:49)
              at new Mc (js?key=MyGoogleAPIKEY&libraries=geometry:49)
             at Object.addListener (js?key=MyGoogleAPIKEY&libraries=geometry:116)
    at Object.addListenerOnce (js?key=MyGoogleAPIKEY&libraries=geometry:117)
    at Maplace.Load (maplace.js:1111)
    at map.html:12

**Script:**
    <script src="https://maps.googleapis.com/maps/api/js?key=MyGoogleAPIKEY&libraries=geometry">
</script>
    </script>
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/maplace.js-master/src/maplace.js"></script>
    <script type="text/javascript">
      var maplace = new Maplace();
      maplace.Load();
    </script>

**HTML**
I have a div block with id=map
    <div id="map"></div>

**Comment by danielemoraschi** [comment]
Is the div block before or after the js include?

**Comment by stonez56** [comment]
I place the div block after the js include as follow:
After seeing your reply just now, I placed div block before and it also didn't work.
I'm using the Chrome browser and  installed XAMPP(Apache/PHP/MySQL) on a Mac calling this map.html from localhost.

I've tested Google tutorial and it showed up the map correctly.
[https://developers.google.com/maps/documentation/javascript/adding-a-google-map](url)

What could be wrong?  Thanks a lot! 👍 

  `  <script src="https://maps.googleapis.com/maps/api/js?key=MyAPI_KEY&libraries=geometry">
    </script>
    </script>
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/maplace.js-master/src/maplace.js"></script>
    <script type="text/javascript">
      var maplace = new Maplace();
      maplace.Load();
    </script>
`
*HTML*
`
    <div id="map"></div>
    <div id="controls"></div>
`

**Comment by joomkit** [comment]
Check if you have two lots of 'new Maplace' and just initialise once

**Comment by danielemoraschi** [comment]
The default div delector as per documentation is `gmap`, and not `map`. 
Please change your code as follow:
```
<div id="gmap"></div>
```
Also, make sure you call the object instantiation `[...] new Maplace() [...]` **after** the div has been placed in the DOM. Your example would not work anyway.
The div block has to placed before the js. Alternatively you can use the standard jQuery helper for when the DOM is fully loaded:
```
$(function() {
  // handler for .ready() called
});
```
