### ISSUE TITLE
How can i get all locations when using Maplace type directions ?

### ISSUE THREAD

**Issue by rescue1155** [danielemoraschi/maplace.js#176]
I am using below code to get all lat long positions.

    new Maplace({
    locations: LocsD,
    map_div: '#gmap-route',
    generate_controls: false,
    show_markers: false,
    type: 'directions',
    draggable: true,
    directions_panel: '#route',
    drag: function(index, location, marker){
        console.log(marker);
    }
}).Load(); 

How can i get all position names or directions routes lat, long. Because i have to get all these points that following from start to destination point.

Thanks

**Comment by danielemoraschi** [comment]
Hi,

Sorry, I'm not sure I understand your question.
How do you want to get all the position names and coordinates, from the drag event?

**Comment by rescue1155** [comment]
Hi, Thanks for your response. 
Yes i want all position names and coordinates that make the route.
For Example: There are two point A and B, When moving from point A to B there are 5 ways.
Here i have to set only one path, For that i need all coordinates that makes this path.

Why I want this ?
I arrange different events from different location from my starting location, So i always tell my clients which route we follow, That's why i need only one path.

**Comment by danielemoraschi** [comment]
Please have a look at the documentation. You can use the `afterRoute` event:
```
afterRoute: function(distance, status, result) {
    console.log(result);
}
```
`result` will contain all the points that makes up the route.

**Comment by rescue1155** [comment]
afterRoute: event not gives me coordinates, Instead it gives mein place IDs. Please find the attached image
![screenshot from 2018-02-20 10-21-27](https://user-images.githubusercontent.com/15667762/36408604-41ccfe2a-1628-11e8-9e6a-32e3a8d1f6cd.png)

If i get all these place_id's, Then how can i withdraw again that same type route again ??

**Comment by danielemoraschi** [comment]
You have all the points in the `routes` array.

**Comment by rescue1155** [comment]
The above solution not worked.
I am unable to find coordinates anywhere in the console.

You can find the attached screenshot
![screenshot from 2018-02-22 12-09-31](https://user-images.githubusercontent.com/15667762/36524962-e2bae016-17c9-11e8-9b0b-427f4b919131.png)

Now we have two options.
1) Can i use place ID instead of location lat long ? because i am getting place IDs.
2) or ANY other appropriate solution where i get get all points that makes the route ?

Looking for your positive response.

**Comment by danielemoraschi** [comment]
You have it:

<img width="661" alt="screen shot 2018-02-22 at 09 13 49" src="https://user-images.githubusercontent.com/872066/36529698-05f4b8b8-17b1-11e8-8f25-3b198e711b29.png">

**Comment by rescue1155** [comment]
DONE, Thanks
Yes i have found it, and coded.
`function showRouteLatLong(result) {
    if(result.routes.length > 0 && result.routes[0].legs[0].via_waypoint.length > 0) {
      for(var i = 0; i < result.routes[0].legs[0].via_waypoint.length ; i++){
          console.log( 'Location:' + result.routes[0].legs[0].via_waypoint[i].location.toString() );
      } 
    }
}`

Now, Can you please show me a demo related to directions_options? So i can draw that waypoints using maplace ?

**Comment by danielemoraschi** [comment]
I'm not sure what you are trying to achieve.

`directions_options ` is just a proxy to GoogleMaps for the following properties:
https://developers.google.com/maps/documentation/javascript/reference#DirectionsRequest

Please refer to the MaplaceJs documentation page.

**Comment by rescue1155** [comment]
Its Done,
I have achieve 75% of what i have to do using maplace.

Now i need to add new markers, when i click the button, and that marker or coordinates create a new route for me.
Same like google maps. You are going to add new locations, It auto drawing the route.

**Comment by danielemoraschi** [comment]
More or less what you need to do is:
- add an `onClick` event to the map (check the `listeners `)
- grab the coordinates from the onClick `event` object
- create a Maplace location object with those coordinates
- add the new location to you locations array
- load/reload the Maplace instance with the updated locations

**Comment by rescue1155** [comment]
HI @danielemoraschi 
I do it using listeners (as you described above message) but i am sorry, it's not worked.

Please have a look to attached screenshot may be it helps you understand what i want achieve next.
![screenshot-map test loc-2018-02-26-10-58-26](https://user-images.githubusercontent.com/15667762/36655500-d82240fe-1ae4-11e8-81f7-24a5568d984f.png)

I want to allow user to enter multiple locations, and draw a route real time.
I have london lat/log, just need to add these on direction map.

**Comment by danielemoraschi** [comment]
Well, there must be something wrong with your implementation :)

**Comment by rescue1155** [comment]
HI @danielemoraschi 
Can you please little bit help me to implementation.
![screenshot from 2018-02-28 16-29-24](https://user-images.githubusercontent.com/15667762/36785562-1232f59c-1ca5-11e8-80df-baf820030b28.png)
Here i have do different variations but unable to set the listeners.

But Here, In input field I have latitude/longitude but re-route not change according to next entered location.
Looking for your response.

**Comment by danielemoraschi** [comment]
This is as far as I can go. Hope it helps:
https://jsfiddle.net/dmoraschi/ozst0u7t

**Comment by rescue1155** [comment]
@danielemoraschi Thanks for you kind words and positive response.
I have done with, what i have to achieve.

Now the only thing i just look now, When i add a location, where i can do in driving mode. Then i am unable to draw further routes. Its stops working or drawing new routes.

Please fins the attached images for your reference.
In google map when i go pakistan to india In driving mode.
![screenshot from 2018-03-06 13-22-17](https://user-images.githubusercontent.com/15667762/37021667-21778bca-2142-11e8-92c3-22524a1842fd.png)

And here is what i have achieved.
![screenshot from 2018-03-06 13-29-31](https://user-images.githubusercontent.com/15667762/37021751-775f2516-2142-11e8-81df-5f9212641f5a.png)
Now when i go to any location where, we can't go without via drive, So then i want to stop it or show an error.
Hope you understand the case.

Thanks

**Comment by rescue1155** [comment]
Second, When i drop the pin A or pin B.
How can i get the latest lat/long of that pin.
I have used dragEnd, dragStart but no luck.
