### ISSUE TITLE
Inline style position: relative breaks my layout any way to prevent it being applied to the map canvas?

### ISSUE THREAD

**Issue by chrisdempsey** [danielemoraschi/maplace.js#184]
On page load the map canvas div has an inline style applied

`<div id="gmap" >` becomes `<div id="gmap" style="position: relative; overflow: hidden;">`

This breaks my layout and I'm trying to override or remove `position: relative`.

I can see it is added by lines 280-284 in maplace.js

```
            try {
                this.map_div.css({
                    position: 'relative',
                    overflow: 'hidden'
                });
```
My javascript isn't that strong, is there any way to override or prevent this with the parameters set during the `new Maplace` call?

I managed to prevent the unwanted behaviour by applying !important to the `position` set on a parent element in my css however that's untidy, I'd rather the inline style wasn't applied at all.

Can anyone point me in the right direction?

**Comment by Carlo-F** [comment]
Hi, 
a possible option is to override the css rules using **JQuery**, immediately after Maplace.Load().

// e.g.
$("#gmap").css('position','fixed').

**Comment by chrisdempsey** [comment]
@Carlo-F Appreciate the suggestion.  I can't remember which website this was in relation to now but will keep this in mind for future.
