### ISSUE TITLE
supressMarkers

### ISSUE THREAD

**Issue by cmnstmntmn** [danielemoraschi/maplace.js#31]
i would like to add **supressMarkers:true** to **directions_options** object

to change to A, B markers icon

![map](https://f.cloud.github.com/assets/2312755/1952855/c7b52352-81b0-11e3-875d-c43e330cf8f5.png)

**Comment by tenKinetic** [comment]
This can be done by switching out the DirectionsRenderer before the markers are displayed.
`
// create the alternate renderer:
var directionsDisplay = new google.maps.DirectionsRenderer({suppressMarkers:true});
// create the map using the beforeViewAll event:
var map = new Maplace({
  option:value,
  option:value,
  beforeViewAll: function() {
    // assign this map to the directionsRenderer:
    directionsDisplay.setMap(map.oMap);
    // replace the directionsRenderer used by Maplace:
    map.directionsDisplay = directionsDisplay;
  }
}).Load();
`
If you are using your own markers, their info_windows will still be non-functional. I think I have seen a separate issue for that. I think this issue can be closed.

**Comment by danielemoraschi** [comment]
I will close this, unfortunately this kind of customisations has to be done "manually".
@tenKinetic Thanks
