### ISSUE TITLE
addLocations without re-center/re-zoom

### ISSUE THREAD

**Issue by claudiof** [danielemoraschi/maplace.js#33]
Hi,

Everytime i call addLocations or add locations via Load(options) the map resets the zoom to the boundaries according to the markers.

It is possible to disable this? Like, add markers but no re-center/re-pan/re-zoom?

**Comment by danielemoraschi** [comment]
Using:
```
map_options: {
    set_center: [<lat>, <lon>],
    zoom: <zoom>
},
```
Will force Maplace to stay on a fixed center location and zoom between different `Load` or `SetLocations` calls. Example: http://jsfiddle.net/_tomorro/p9nxn0tf/
