### ISSUE TITLE
Custom Icons?

### ISSUE THREAD

**Issue by jezthomp** [danielemoraschi/maplace.js#37]
The main maplace says 'Markers and custom icons’ but i cannot find any documentation of how to accomplish this, is it possible with the current release?

**Comment by Nucleo1985** [comment]
Hi,

First to say very nice plugin for maps. But im facing some issue here. I used oprtions like below:

locations        : [
                {
                    lat: -6.210122,
                    lon: 106.848057
                },
                {
                    lat: -6.914863,
                    lon: 107.608413
                },
            ],
            map_div          : '#route_map',
            type             : 'directions',
            directions_panel : '#directions',
            map_options      : {
                zoom             : 16,
                disableDefaultUI : true,
                streetViewControl: false,
                mapTypeControl   : false,
            },
            generate_controls: false,
            show_markers     : false,
            draggable        : true,

what i want to ask is, even i change the zoom option value its didnt take effect not zoom in and zoom out. 
Second, the icon options for marker. even i setup icon option like this icon: '/assets/img/marker.png' or document.location.origin + '/assets/img/marker.png' the marker did not change.

Any clue for this issue? anything else, very nice to used.

Thank you very much,

Nucleo1985
