### ISSUE TITLE
It works pretty well ^_^, can I disable zooming with mouse wheel?

### ISSUE THREAD

**Issue by gudh** [danielemoraschi/maplace.js#4]
It works pretty well ^_^, can I disable zooming with mouse wheel? It's very annoying,  the map zooms everytime I scrolling down the page with mouse wheel.

**Comment by VeeK727** [comment]
Hey Daniel, I'm getting an error with your code.
`map.setOptions is not a function`
Here's the whole thing
```
var map = new Maplace({
    map_options: {
      set_center: [lat, lon],
      zoom: 15,
      scrollwheel: false
    },
    locations: [{
    	lat: lat,
    	lon: lon
    }],
    listeners: {
    	click: function(map, event) {
        map.setOptions({
            scrollwheel: true
        });
    	}
    }
}).Load();
```

**Comment by weilinzung** [comment]
@danielemoraschi  @VeeK727  I am getting the same errors.

**Comment by weilinzung** [comment]
@VeeK727 try to change this one`map.setOptions({` to `this.setOptions({`. Should works!
