### ISSUE TITLE
Mixed / Ajax

### ISSUE THREAD

**Issue by puertotorres** [danielemoraschi/maplace.js#42]
First thank this great plugin for jquery. I have a question that keeps me awake. I am making an app in jquery mobile and I'm trying to adapt a menu in the footer to allow changing of maps, as in the example have "Mixed / Ajax". But I can not see the map. I show the code to you to check where it can be the fault. 

I would appreciate your help. 
Thank you.

<html>
    <head>
        <title>Mapas</title>
        <meta name="viewport" content="initial-scale=1, maximum-scale=1"/>      

```
    <!-- FontAwesome - http://fortawesome.github.io/Font-Awesome/ -->
    <link rel="stylesheet" href="css/font-awesome.min.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>

    <!-- jQueryMobileCSS - original without styling -->
    <link rel="stylesheet" href="css/jquerymobile.css" />

    <!-- nativeDroid core CSS -->
    <link rel="stylesheet" href="css/jquerymobile.nativedroid.css" />

    <!-- nativeDroid: Light/Dark -->
    <link rel="stylesheet" href="css/jquerymobile.nativedroid.light.css"  id='jQMnDTheme' />

    <!-- nativeDroid: Color Schemes -->
    <link href="css/jquerymobile.nativedroid.color.green.css" rel="stylesheet" type="text/css" id='jQMnDColor' />


    <style>
        #content {
            padding: 0;
            position : absolute !important;
            top : 50px !important;
            right : 0;
            bottom : 62px !important;
            left : 0 !important;
            }

    </style>        
    <!-- jQuery / jQueryMobile Scripts -->

    <script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.9.0.min.js"></script>


       <script type="text/javascript">
                var maplace = new Maplace({
                    map_div: '#gmap-mixed',
                    controls_div: '#controls-mixed',
                    controls_type: 'list',
                    controls_on_map: false
                });

                $('#tabs a').click(function(e) {
                    e.preventDefault();
                    var index = $(this).attr('data-load');
                    showGroup(index);
                });

                function showGroup(index) {
                    var el = $('#g'+index);
                    $('#tabs li').removeClass('active');
                    $(el).parent().addClass('active');
                    $.getJSON('data/ajax.php', { type: index }, function(data) {
                        //loads data into the map
                        maplace.Load({
                            locations: data.locations,
                            view_all_text: data.title,
                            type: data.type,
                            force_generate_controls: true
                        });
                    });
                }

                showGroup(0);
            </script>
```

</head>                         

<body>

```
<div data-role="page">


       <body data-nativedroid-progress-animation='6'>
```

<div data-role="header" data-position="fixed" data-tap-toggle="false" data-theme='b'>
            <a href="index.html" data-role='button' data-icon='angle-left' data-transition="slide" data-rel="back" data-iconpos="notext" data-ajax="true" data-inline='true'>Volver</a>
            <h1 style="text-align: center"><img src="images/icon/vdk-320b.png" width="32" height="23"  alt=""/> <span style="color: #33B5E5">Alojamiento</span></h1>
            <a href="#mypanel" data-role='button' data-icon='tasks' data-iconpos="notext" data-inline='true'>Menu</a>
        </div>
        

<div data-role="page" data-theme="b">

    <div data-role="panel" id="mypanel" data-theme="b">
        <ul data-role="listview">
            <li data-role="list-divider">Menu</li>
            <li data-icon="home"><a href="index.html">Inicio</a></li>
            <li data-icon="user"><a href="01_club.html">Club Birding</a></li>
            <li data-icon="check"><a href="02_socios.html">Planifica tu ruta</a></li>
            <li data-icon="map-marker"><a href="#">Rutas</a></li>
            <li data-icon="flag-checkered"><a href="#">Mapa de rutas</a></li>
            <li data-icon="picture"><a href="#">H&aacute;bitat</a></li>
            <li data-icon="camera"><a href="#">Especies</a></li>
            <li data-icon="volume-up"><a href="#">Sonidos</a></li>
        </ul>
    </div>

   </div>
           <div data-role="footer" data-position="fixed" data-tap-toggle="false">
           <div data-role="navbar">
           <ul id="tabs">
  <li><a href="javascript:void(0)" data-load="0" id="g0" title="Group A">Group A</a></li>
  <li><a href="javascript:void(0)" data-load="1" id="g1" title="Group B">Group B</a></li>
  <li><a href="javascript:void(0)" data-load="2" id="g2" title="Group C">Group C</a></li>
  <li><a href="javascript:void(0)" data-load="3" id="g3" title="Group D">Group D</a></li>
  <li><a href="javascript:void(0)" data-load="4" id="g4" title="Group E">Group E</a></li>
</ul>
           <div id="gmap-mixed" style="height:100%"></div>
           <div id="controls-mixed"></div>
![screenshot_1](https://cloud.githubusercontent.com/assets/6523507/2565835/105c7a24-b8bb-11e3-81a4-75b0eb9b1922.jpg)

```
    <script src="js/nativedroid.script.js"></script>
        <script src="http://maps.google.com/maps/api/js?sensor=false&amp;libraries=geometry&amp;v=3.7?1343675510"></script>
<script src="javascripts/libs.min.js?v=0.1.2b"></script>

<script src="src/maplace.min.js?v=0.1.2c"></script>

<script src="data/points.js?v=0.1.2b"></script> 
<script src="javascripts/app.js?v=0.1.2b"></script>


</body>
```

</html>

**Comment by danielemoraschi** [comment]
Closing this as related to an implementation issue rather than library.
