### ISSUE TITLE
two streets within one city tab

### ISSUE THREAD

**Issue by Merluzza** [danielemoraschi/maplace.js#44]
Hi, thanks for nice map project. i have an issue as for the tabs. Let's say i have my tabs with three cities: | City 1 | City 2 | City 3| . Each city shows its own one street ecxept | city 2 | that shows two streets with markers. My question is how to show two streets with its markers within one tab. 
![tabs](https://cloud.githubusercontent.com/assets/6797033/2659326/1c9faedc-c013-11e3-96dc-d882e57f38ef.jpg)
here is my code:

//pointers
var LocsB = [

```
{lat: 50.449707, lon: 30.505129, title: 'City 1', 
 html: [ '<h4>Street 1</h4>'].join(''), zoom: 15},

 {lat: 49.069074, lon: 33.411325, title: 'City 2',
 html: ['<h4>Street 1</h4>','<h4>Street 2</h4>'].join(''), zoom: 15},

 {lat:49.068078, lon: 33.417038, title: 'City 3',
 html: ['<h4>Street 1</h4>'].join(''), zoom: 15}
];
```

 //mapPlace
new Maplace({
    locations: LocsB,
    map_div: '#gmap-tabs',
    controls_div: '#controls-tabs',
    controls_type: 'list',
    controls_on_map: false,
    show_infowindow: true,
    start: 1,
    afterShow: function(index, location, marker) {
        $('#info').html(location.html);
    }
}).Load(); 

//script

<script src="http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7"></script>

<script src="js/maplace.min.js"></script>

<script src="http://code.jquery.com/jquery-1.9.0.min.js"></script>

<script src="js/pointers.js"></script> 

<script src="js/mapPlace.js"></script>

**Comment by danielemoraschi** [comment]
Closing this as related to a presentation issue rather than library. For instance, something like:
http://jsfiddle.net/_tomorro/fyxb8ngf/
Should do the trick (with some CSS sugar to transform the `h2` elements into tabs).
