### ISSUE TITLE
Change google.maps.TravelMode.

### ISSUE THREAD

**Issue by voltan** [danielemoraschi/maplace.js#51]
Hello
How I can add option for select `google.maps.TravelMode.` by user, I use directions_options and I can change it manually on codes , But I need select panel for users 

like https://www.google.fr/maps/dir/Ristolas/Lacs+Lacroix+ou+de+S%C3%A9gure/@44.75139,6.9133453,13z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x12ccd38e9eb68007:0x40819a5fd97a3d0!2m2!1d6.955228!2d44.7739339!1m5!1m1!1s0x12ccd236e01a82b7:0x9e8884a9570fc567!2m2!1d6.955849!2d44.728924!3e2

**Comment by danielemoraschi** [comment]
Yes it will, using the `directions_options` options as per documentation.
