### ISSUE TITLE
marker move in real time

### ISSUE THREAD

**Issue by thailemon** [danielemoraschi/maplace.js#56]
trying to move marker in real time, without refreshing or .Load()ing.

i can center the map to the new position, but the marker/icon isn't following.
any suggestions?

so far i have
maplace.markers[0].lat = coordLat;
maplace.markers[0].lon = coordLong;
maplace.markers[0].zoom = "16";
maplace.markers[0].icon = "images/marker.png";
maplace.markers[0].position.d = coordLat;
maplace.markers[0].position.e = coordLong;

**Comment by danielemoraschi** [comment]
Quite a late reply, but maybe useful for others:
http://jsfiddle.net/_tomorro/fxLf3woa/3/
