### ISSUE TITLE
Disable Autocenter when click on a Marker

### ISSUE THREAD

**Issue by ricardmc** [danielemoraschi/maplace.js#57]
Is it possible to disable the "auto-center" movement when I click on a marker?

I tried to use .setCenter() but it is just a googleMaps function, not a Maplace function.

Any solution? thanks!

**Comment by VeeK727** [comment]
Umm...what are you talking about? I don't see any 'pan_on_click' option in your documentation or google maps' options. I also need to disable the auto center feature.

**Comment by danielemoraschi** [comment]
True, it's not documented but actually implemented:
https://github.com/danielemoraschi/maplace.js/blob/master/src/maplace.js#L183
