### ISSUE TITLE
Maplace doesn't work if locations contain only one marker

### ISSUE THREAD

**Issue by nguyenvuduc** [danielemoraschi/maplace.js#65]
Hi, Daniele,

Thank you very much for this awesome plugin.
I realized that the version 0.1.3 of maplace doesn't work when locations contain only one marker.
Below is the code for reproducing the issue.

Thank you.

```html

<html>
<body>
<script src="http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7">
</script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://maplacejs.com/src/maplace-0.1.3.js"></script>



<div id="myMap" style="width:300px;height:200px">
</div>

<script>
	jQuery(document).ready(function(){
		new Maplace({
			map_div:'#myMap',
			type:'marker',
			locations:[{
				lat:0,
				lon:0,
				html:'Hello'
			}]
		}).Load();
	});
</script>	
</body>
</html>
```

**Comment by fikilek** [comment]
I tried this example in my local machine and it does not work. Can someone explain please. I used as is with the addition of the Google API key.

**Comment by danielemoraschi** [comment]
Here's a working example, hope this helps:
https://jsfiddle.net/_tomorro/8op9jm9d/2/

**Comment by fikilek** [comment]
Tnx a lot. I’m now sorted
