### ISSUE TITLE
Directions infowindow

### ISSUE THREAD

**Issue by kwstassv** [danielemoraschi/maplace.js#70]
Hi,
In directions mode doesnt show costum title and html in infowindows, only showing the address...

how i can fix this and show custum title and html in infowindows?

**Comment by regisphilibert** [comment]
Same problem here, the title and/or html value of the locations items seems to be ignored in 'direction' mode. When clicking on the info window, only the address is displayed.

**Comment by tenKinetic** [comment]
This can be accomplished by manually constructing the info objects for the markers in the beforeViewAll event.
Assuming you had used the usual method of using the html property of locations:
```
var map = new Maplace({
	locations: locations,
	map_div: '#id',
	generate_controls: false,
	show_markers: true,
	type: 'directions',
	pan_on_click: false,
	beforeViewAll: function() {
		for (i=0;i<map.markers.length;i++) {
			var marker = map.markers[i];
			marker.info = new google.maps.InfoWindow({
				content:marker.html
			});
			google.maps.event.addListener(marker, 'click', (function(marker, i) {
				return function() {
					marker.info.open(map.oMap, map.markers[i]);
				}
			})(marker, i));
		}
	}
}).Load();
```
This issue can probably be closed. Shame github doesn't have Close Issue requests.

**Comment by danielemoraschi** [comment]
@tenKinetic Thanks for your help!
