### ISSUE TITLE
AddLocations parameter

### ISSUE THREAD

**Issue by gitllermopalafox** [danielemoraschi/maplace.js#72]
Hi,

I have qustion about "AddLocations" method:

This is how I'm implementing the method:

var map = new Maplace({
    map_div: '#map',
    ...
});
var point = {
        lat: 20.595691,
        lon: -105.222147,
        animation: google.maps.Animation.DROP
};
map.AddLocations(point);

When I do not set the reload parameter to the AddLocations method the location/marker it doesn't appear (I assume that reload parameter is false by the default), but when I set reload to true, the location/marker appears.

My question is: Does the reload parameter is mandatory to set it "true"?

Thanks.

**Comment by danielemoraschi** [comment]
Yes, reload is false by default hence you need to pass true if you want to updated your map.
This is because not always you want to update you map but has to be an intentional decision.
