### ISSUE TITLE
Arrow Icon instead of Circle dots while dragging

### ISSUE THREAD

**Issue by jitujazz** [danielemoraschi/maplace.js#76]
Is it possible to set an arrow icon on the four edges of the circle and maybe a tooltip with it to say "Drag This"?

**Comment by danielemoraschi** [comment]
Please refer to Google documentation:
https://developers.google.com/maps/documentation/javascript/reference#CircleOptions

The tooltip can be the title of your marker like in my example: http://maplacejs.com/#radiusInfo
