### ISSUE TITLE
Address input field for directions mode

### ISSUE THREAD

**Issue by appel** [danielemoraschi/maplace.js#8]
This would make a great addition to an already great plugin!

**Comment by lenamtl** [comment]
+1

**Comment by lenamtl** [comment]
I need this feature too.
I have found this tutorial: http://www.dreamdealer.nl/tutorials/using_geolocation_to_automatically_generate_a_route_and_directions_in_google_maps.html

**Comment by danielemoraschi** [comment]
Related to #126
