### ISSUE TITLE
Map is not fully rendered on Twitter Bootstrap modal

### ISSUE THREAD

**Issue by matriphe** [danielemoraschi/maplace.js#83]
I embeded Maplace inside modal, the map is not fully rendered. See the example here: http://jsfiddle.net/tnp9zc5b/

How to make it fully renderred?

**Comment by danielemoraschi** [comment]
Hi, please replace:
```
$('#myModal').on('show.bs.modal', function (event) {
```
with:
```
$('#myModal').on('shown.bs.modal', function (event) {
```

**shown.bs.modal** instead of **show.bs.modal**

**Comment by matriphe** [comment]
@danielemoraschi yes! that's worked! thanks!

**Comment by fikilek** [comment]
I just started using Maplace.js. I works when I do the example but fails when I integrate it with my other development work.

Here is my scenarios. I have a main menu (bootstrap) that open a div with two tabs. One tab displays a table from MySQL db and the other tab should display a map of the points on the table.

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>iREPS</title>
	
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	
	<script src="https://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.22&key=Google Key"></script>
		
	
	<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
	<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>	

	
	<script src="maplace.min.js"></script>

	<style>
		#mapcanvas {
		    width: 100%px; 
		    height: 500px;
		}
	</style>

	<script type="text/javascript">
		var i;
		$(document).ready(function() {


			$("#id_erf_main_menu").click(function (e) {
				//debugger;
				e.preventDefault();
				jQuery.ajax({
					type: "POST", // HTTP method POST or GET
					url: "jq_erf_dbquery.php", //Where to make Ajax calls
					dataType:"json", // Data type, HTML, json etc.
					//data:myData, //Form variables
					success:function(erfArray){
						//Display ERFS Table
						displayErfsTable(erfArray);
						displayErfsMap(erfArray);
					},
				});
			});
			
			//
		});	
	</script>
</head>

<body>
<div id="main_menu">
			<nav class="navbar navbar-default" style="min-height: 0;">
				
				<ul class="nav nav-pills">
					<li class="active"><a data-toggle="tab" href="#municipalities">Municipalities</a></li>
					<li><a data-toggle="tab" href="#contracotrs">Contractors</a></li>
					<li><a data-toggle="tab" href="#fws">Field Workers</a></li>
					<li><a data-toggle="tab" href="#devices">Devices</a></li>
					<li><a data-toggle="tab" href="#erfs" id="id_erf_main_menu">ERFs</a></li>
					<li><a data-toggle="tab" href="#wos">Works Orders</a></li>
					<li><a data-toggle="tab" href="#dashboard">Dashboard</a></li>
					<li><a data-toggle="tab" href="#assets">Assets</a></li>
				</ul>
			</nav> 
</div>

			<div class="tab-content">
				<div id="municipalities" class="tab-pane fade in active">
					<p>Municipalities Windows</p>
				</div>
				<div id="contracotrs" class="tab-pane fade">
					<p>Contractors Windows</p>
				</div>
				<div id="fws" class="tab-pane fade">
					<p>Field Workers Windows</p>
				</div>
				<div id="devices" class="tab-pane fade">
					<p>Devices Windows</p>
				</div>
				<div id="wos" class="tab-pane fade ">
					<p>WOs  goes here.</p>
				</div>
				<div id="dashboard" class="tab-pane fade">
					<p>Dashboard data displays here.</p>
				</div>
				<div id="assets" class="tab-pane fade">
					<p>Assets data displays here.</p>
				</div>				
				<div id="erfs" class="tab-pane fade" >


					<ul class="nav nav-tabs" id="erfTab">
					  <li class="active"><a href="#tab1">ERF Table</a></li>
					  <li><a href="#tab2">ERF Map</a></li>
					</ul>



					<div class="tab-content">
					  	<div class="tab-pane active" id="tab1">
					  	<p> ERF Table tab </p>
		 	          		<table id="erfTable" class="table table-striped" >
	           				</table>
					  	</div>
						<div class="tab-pane" id="tab2">
						<p> ERF Map tab </p>
						<div id="mapcanvas"></div>						
					</div>						
				</div>
			</div>


	<script>
		function displayErfsTable(erfArray) {
			$("#erfTable").append("<thead>");
				$("#erfTable").append("<tr>");
				$("#erfTable").append("<th>ERF No</th>");
				$("#erfTable").append("<th>area Name</th>");
				$("#erfTable").append("<th>lat</th>");
				$("#erfTable").append("<th>long</th>");	
				$("#erfTable").append("</tr>");	
			$("#erfTable").append("</thead>");
		    // Display each row in the ERFs Table 
		    for( i = 0; i < erfArray.length; i++ ) {
	  				var  erfRow = erfArray[i];
	  				$("#erfTable").append("<tr>");
			    	$("#erfTable").append("<td> " + erfRow['erf_no'] + " </td>");
			    	$("#erfTable").append("<td> " + erfRow['an'] + " </td>");
			    	$("#erfTable").append("<td> " + erfRow['latitude'] + " </td>");    	    	
			    	$("#erfTable").append("<td> " + erfRow['longitude'] + " </td>");    	
				$("#erfTable").append("</tr>");
			}
			//
			$("#erfTable").append("<thead>");
				$("#erfTable").append("<tr>");
					$("#erfTable").append("<th>ERF No</th>");
					$("#erfTable").append("<th>area Name</th>");
					$("#erfTable").append("<th>lat</th>");
					$("#erfTable").append("<th>long</th>");	
				$("#erfTable").append("</tr>");	
			$("#erfTable").append("</thead>");	
		}

		function displayErfsMap(erfArray) {
			$(function() {
				debugger;
				new Maplace({
					locations: [
						{
							lat: -31.069914,  
							lon: 28.352987,
							zoom: 16,
							map_div: "mapcanvas"
						}
					],
			        controls_on_map: false
				}).Load(); 
			});
		}

	</script>

</body>
</html>

**Comment by danielemoraschi** [comment]
Few things:

- Invalid CSS for `#mapcanvas{ width: 100%px; ...` % or px?
- `#id_erf_main_menu` doesn't exists in your html, how do you trigger the `click` event?
- Your data array looks like contains keys `latitude` and `longitude`, Maplace use `lat` and `lon`
- Inside `displayErfsMap` you need to move out `map_div: "mapcanvas"` **outside** the `locations` parameters.

I sure there's more.

**Comment by fikilek** [comment]
tnx Daniel

--Invalid CSS for #mapcanvas{ width: 100%px; ... % or px?
--[I corrected this mistake]

--#id_erf_main_menu doesn't exists in your html, how do you trigger the click event?
--[#id_erf_main_menu is in the ERFs menu], see below.
----------------------------------------------------
			<nav class="navbar navbar-default" style="min-height: 0;">
				
				<ul class="nav nav-pills">
					<li class="active"><a data-toggle="tab" href="#municipalities">Municipalities</a></li>
					<li><a data-toggle="tab" href="#contracotrs">Contractors</a></li>
					<li><a data-toggle="tab" href="#fws">Field Workers</a></li>
					<li><a data-toggle="tab" href="#devices">Devices</a></li>
					<li><a data-toggle="tab" href="#erfs" id="id_erf_main_menu">ERFs</a></li>
					<li><a data-toggle="tab" href="#wos">Works Orders</a></li>
					<li><a data-toggle="tab" href="#dashboard">Dashboard</a></li>
					<li><a data-toggle="tab" href="#assets">Assets</a></li>
				</ul>
			</nav> 
----------------------------------------------------

--Your data array have keys latitude and longitude, Maplace use lat and lon
--[I commmented this out for now as I want to see just the map displayed for now. But still my map does not show.]

--Inside displayErfsMap you need to move map_div: "mapcanvas" outside the locations parameters.
--[I moved it out]

--Inside displayErfsMap you need to change map_div:'mapcanvas', to become map_div:'#mapcanvas',
--[I corrected it]

See my updated code below.  It still does not work. I tried all day.
-------------------------------------------------------------------------------------------

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>iREPS</title>
	
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	
	<script src="https://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.22&key=KEY"></script>
		
	
	<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
	<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>	

	
	<script src="maplace.min.js"></script>

	<style>
		#mapcanvas {
		    width: 100%; 
		    height: 500px;
		}
	</style>

	<script type="text/javascript">
		var i;
		$(document).ready(function() {
			$("#id_erf_main_menu").click(function (e) {
				debugger;
				e.preventDefault();
				jQuery.ajax({
					type: "POST", // HTTP method POST or GET
					url: "jq_erf_dbquery.php", //Where to make Ajax calls
					dataType:"json", // Data type, HTML, json etc.
					//data:myData, //Form variables
					success:function(erfArray){
						//Display ERFS Table
						displayErfsTable(erfArray);
						//console.log(erfArray);
						displayErfsMap(erfArray);
					},
				});
			});
		});	
	</script>
</head>

<body>
	<div id="main_menu">
		<nav class="navbar navbar-default" style="min-height: 0;">
			
			<ul class="nav nav-pills">
				<li class="active"><a data-toggle="tab" href="#municipalities">Municipalities</a></li>
				<li><a data-toggle="tab" href="#contracotrs">Contractors</a></li>
				<li><a data-toggle="tab" href="#fws">Field Workers</a></li>
				<li><a data-toggle="tab" href="#devices">Devices</a></li>
				<li><a data-toggle="tab" href="#erfs" id="id_erf_main_menu">ERFs</a></li>
				<li><a data-toggle="tab" href="#wos">Works Orders</a></li>
				<li><a data-toggle="tab" href="#dashboard">Dashboard</a></li>
				<li><a data-toggle="tab" href="#assets">Assets</a></li>
			</ul>
		</nav> 
	</div>

	<div class="tab-content">
		<div id="municipalities" class="tab-pane fade in active">
			<p>Municipalities Windows</p>
		</div>
		<div id="contracotrs" class="tab-pane fade">
			<p>Contractors Windows</p>
		</div>
		<div id="fws" class="tab-pane fade">
			<p>Field Workers Windows</p>
		</div>
		<div id="devices" class="tab-pane fade">
			<p>Devices Windows</p>
		</div>
		<div id="wos" class="tab-pane fade ">
			<p>WOs  goes here.</p>
		</div>
		<div id="dashboard" class="tab-pane fade">
			<p>Dashboard data displays here.</p>
		</div>
		<div id="assets" class="tab-pane fade">
			<p>Assets data displays here.</p>
		</div>				
		<div id="erfs" class="tab-pane fade" >
			<ul class="nav nav-tabs" id="erfTab">
			  <li class="active"><a href="#tab1">ERF Table</a></li>
			  <li><a href="#tab2">ERF Map</a></li>
			</ul>
			<div class="tab-content">
			  	<div class="tab-pane active" id="tab1">
			  	<p> ERF Table tab </p>
 	          		<table id="erfTable" class="table table-striped" >
          				</table>
			  	</div>
				<div class="tab-pane" id="tab2">
				<p> ERF Map tab </p>
				<div id="mapcanvas"></div>						
			</div>						
		</div>
	</div>
	<script>
		function displayErfsTable(erfArray) {
			$("#erfTable").append("<thead>");
				$("#erfTable").append("<tr>");
				$("#erfTable").append("<th>ERF No</th>");
				$("#erfTable").append("<th>area Name</th>");
				$("#erfTable").append("<th>lat</th>");
				$("#erfTable").append("<th>long</th>");	
				$("#erfTable").append("</tr>");	
			$("#erfTable").append("</thead>");
		    // Display each row in the ERFs Table 
		    for( i = 0; i < erfArray.length; i++ ) {
	  				var  erfRow = erfArray[i];
	  				$("#erfTable").append("<tr>");
			    	$("#erfTable").append("<td> " + erfRow['erf_no'] + " </td>");
			    	$("#erfTable").append("<td> " + erfRow['an'] + " </td>");
			    	$("#erfTable").append("<td> " + erfRow['latitude'] + " </td>");    	    	
			    	$("#erfTable").append("<td> " + erfRow['longitude'] + " </td>");    	
				$("#erfTable").append("</tr>");
			}
			//
			$("#erfTable").append("<thead>");
				$("#erfTable").append("<tr>");
					$("#erfTable").append("<th>ERF No</th>");
					$("#erfTable").append("<th>area Name</th>");
					$("#erfTable").append("<th>lat</th>");
					$("#erfTable").append("<th>long</th>");	
				$("#erfTable").append("</tr>");	
			$("#erfTable").append("</thead>");	
		}

		function displayErfsMap(erfArray) {
			$(function() {
				debugger;
				//console.log(map);
			    new Maplace({
			            map_div:'#map_canvas',
			            //type:'marker',
			            locations:[{
			                lat: -31.069914,
			                lon: 28.35298,
			                html:'ERF1',
			                zoom:16
			            }]
			        }).Load();   
			});
		}
	</script>
</body>
</html>

**Comment by danielemoraschi** [comment]
Not sure where the problem is with your code, but works for me. You can try using this fiddle:
https://jsfiddle.net/_tomorro/fyxb8ngf/2/
