### ISSUE TITLE
Menu controls not list or dropdown

### ISSUE THREAD

**Issue by Mik75** [danielemoraschi/maplace.js#84]
hello...is it possible to use single direct link instead of the generated menu list or dropdown? i would like to create separate buttons in my content that view each single location once clicked. thank you

**Comment by danielemoraschi** [comment]
You can use "ViewOnMap"
Docs: https://github.com/danielemoraschi/maplace.js#methods

```
var myMap = new Maplace({...});

myMap.ViewOnMap('all'); // view all
myMap.ViewOnMap(1); // first link
myMap.ViewOnMap(1); // second link
```
