### ISSUE TITLE
CSS problem to view Mixed/ajax tabs 

### ISSUE THREAD

**Issue by talivanxxx** [danielemoraschi/maplace.js#85]
I would like to see the Mixed / Ajax example in its minimal expression of css for tabs or part of jquery tabs.
as I can display the menu excluding all libs.min code and css?

![tabs](https://cloud.githubusercontent.com/assets/10987433/6182668/5984ef62-b30e-11e4-8f8a-b02e203c064f.png)

**Comment by danielemoraschi** [comment]
Probably a bit over-complicated, but this is the best I can do for now:
http://jsfiddle.net/_tomorro/7r5xhhpj/1/

**Comment by talivanxxx** [comment]
thanks !
i want to do layers of polylines, marks and circles and show hide with a toggle button in a map static only change de layer of lines or marks with buttons.
how can i  to do this ?

**Comment by danielemoraschi** [comment]
Please refer to the issue #78

**Comment by talivanxxx** [comment]
thank you very much for answering.
Yes, but the map is moved. I want to do something like this map. SOBERPONER press the button (at the bottom ), but with routes , polylines and marks .
Pressing each button hides or displays each option without the map change.

http://mapoteca.educ.ar/mapa/republica-argentina/

any advice on how to do or google maps API ?
