### ISSUE TITLE
How I can show and hide layers with buttons ?

### ISSUE THREAD

**Issue by talivanxxx** [danielemoraschi/maplace.js#87]
How I can show and hide layers with external buttons in a static map ? 
show and hide marks, lines and routes without the map to move.
I want to do some like this, but with a menu buttons in a static map.  

https://www.google.com/maps/d/edit?mid=zCeGmMuU0rQg.kzN3kb457_zI

any idea how to do it with apiv3 or otherwise ?

**Comment by danielemoraschi** [comment]
Please refer to the issue #78
As already said, there is not a proper way to do it at the moment.
