### ISSUE TITLE
Access instance of Maplace once created

### ISSUE THREAD

**Issue by etichenor** [danielemoraschi/maplace.js#89]
I was wondering if you could give a hint as to how to access the Maplace object after its instantiated from other scripts down the line. At the time I create Maplace in the index.html, I don't have the Locations array ready. I would like to call SetLocations occasionally as those may change. Can you give a sample as to how to call the available functions after the object is created?
Great plugin by the way!

**Comment by danielemoraschi** [comment]
I'm not sure If I get the problem, could it be helpful this demo?
http://jsfiddle.net/_tomorro/symh6psj/2/

**Comment by etichenor** [comment]
I figured this out. Being new to jQuery it took me a bit to rewrite the code that was provided in the examples to that which I needed for my purpose. Your fiddle is exactly what I ended up with. Thanks for getting back to me in any case.
