### ISSUE TITLE
How to add polygon area like this

### ISSUE THREAD

**Issue by RedEars** [danielemoraschi/maplace.js#90]
Hello,
I can't get how to add a polygon area (without drag/resize/etc) like this:
https://www.google.com/maps/d/viewer?msa=0&mid=zzCcHNH4E7bM.k4YEr5hFoIT8

Besides this, I want to show Markers. 
I would appreciate any help. 

Thanks

**Comment by mradzinski** [comment]
I've been trying the same, but it seems the plugin is designed to only allow one polygon per map, so I don't think you'll be capable of creating such a thing :disappointed:
