### ISSUE TITLE
Is there a way to stop the map centring when a pointer is clicked

### ISSUE THREAD

**Issue by liamhen** [danielemoraschi/maplace.js#96]
Is there away to always keep the map centered even if a pointer is clicked as when adding center to map options it gets ignored when more then one pointer is added.

center: new google.maps.LatLng(-34.397, 150.644)

**Comment by braindeavors** [comment]
To center, use set_center inside a map_options object. To disable re-centering on click, use pan_on_click: false

		var maplace = new Maplace({
		    locations: yourLocationsObjectHere,
		    map_div: '#gmap',
		    map_options: { // Normal Google options
		        set_center: [30.893324, 25.258449], // Egypt
		        zoom: 2 // Almost all the way out
		    }, 
		    pan_on_click: false, // Prevents autocentering
                    controls_type: 'list',
		    controls_on_map: false
                });
