### ISSUE TITLE
Places functionality - "save a place"

### ISSUE THREAD

**Issue by scottybo** [danielemoraschi/maplace.js#98]
I was hoping to add this functionality: https://developers.google.com/maps/documentation/javascript/examples/save-infowindow

But it seems this isn't a function in Maplace- any suggestions on how to achieve it? I've enabled sign in ability by changing the include js to https://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.exp&signed_in=true

**Comment by danielemoraschi** [comment]
Closing this as the signed-in feature has been deprecated: https://developers.google.com/maps/documentation/javascript/examples/save-infowindow
