### ISSUE TITLE
Custom SVG market using map-icons

### ISSUE THREAD

**Issue by lajpatshah** [danielemoraschi/maplace.js#99]
Hi

I want to use http://map-icons.com/#markers along with maplace. 

Can you please guide me on that

Thanks

Lajpat

**Comment by danielemoraschi** [comment]
Hi,
just replace the icon property in your location object with the SVG:

```
var MAP_PIN = 'M0-165c-27.618 0-50 21.966-50 49.054C-50-88.849 0 0 0 0s50-88.849 50-115.946C50-143.034 27.605-165 0-165z';

var locations = [
    {
        lat: 45.9,
        lon: 10.9,
        title: 'Title A1',
        html: '<h3>Content A1</h3>',
        icon: {
            path: MAP_PIN,
       	    fillColor: '#0E77E9',
            fillOpacity: 1,
            strokeColor: '',
            strokeWeight: 0,
            scale: 1/2
        },
        animation: google.maps.Animation.DROP
    },
```

**Comment by lajpatshah** [comment]
Hi Daniel

Thanks. But I am facing a small issue with this.

I have to supply label: '<i class="map-icon-parking"></i>' as shown on http://map-icons.com/#usage
But Maplace doesnt shows the label, it only shows the marker.

Can you plz tell how can I show label as well.

Regards
Lajpat
